
version: 2
jobs:

  build:
    environment:
       COVERALLS_REPO_TOKEN: UufMjgYuCcDAmDVFFUy9pE58uoFVP8JCB
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps

      - run: rm -rf ~/repo/artifacts
      - run: mkdir ~/repo/artifacts
      - run:
          name: Install miniconda and dependencies
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh
            ./miniconda.sh -b -f
            export PATH=~/miniconda3/bin/conda
            conda install -c anaconda --yes setuptools
            ~/miniconda3/bin/conda install python=3.6.8 --file requirements.txt --yes
            ~/miniconda3/bin/pip install nose nose-cov python-coveralls
            ~/miniconda3/bin/pip install -e .

      # run all of the tests
      - run:
          name: Run tests and coveralls
          command: |
            ~/miniconda3/bin/nosetests -v tests --with-coverage --cover-package=factor_analyzer --cov-config .coveragerc
            cd ~/repo/factor_analyzer && ~/miniconda3/bin/coveralls

      - store_artifacts:
          path:  ~/repo/artifacts
          destination:  artifacts
