{% set name = "factor_analyzer" %}
{% set version = "0.3.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "94ea4c7d46e846cc7174787adce47156cf58dc257905c878edc5181b4fa300ed" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path : ../../../factor_analyzer

build:
  number: 0
  entry_points:
    - factor_analyzer = factor_analyzer.analyze:main
  script:
    - cd $SRC_DIR
    - $PYTHON setup.py install

requirements:
  build:
    - python==3.6
    - setuptools
    - pandas
    - scipy
    - numpy
    - scikit-learn
  run:
    - python==3.6
    - pandas
    - scipy
    - numpy
    - scikit-learn

test:
  imports:
    - factor_analyzer
  commands:
    - factor_analyzer --help

about:
  home: https://github.com/EducationalTestingService/factor_analyzer
  license: GPL V2
  license_family: GPL
  summary: Exploratory factor analysis in Python
