{% set name = "factor_analyzer" %}
{% set version = "0.3.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "94ea4c7d46e846cc7174787adce47156cf58dc257905c878edc5181b4fa300ed" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path : ../../../factor_analyzer

build:
  number: 0
  noarch: python
  script:
    - cd $SRC_DIR
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.6
    - setuptools
    - pandas
    - scipy
    - numpy
    - scikit-learn
  run:
    - python >=3.6
    - pandas
    - scipy
    - numpy
    - scikit-learn

test:
  imports:
    - factor_analyzer

about:
  home: https://github.com/EducationalTestingService/factor_analyzer
  license: GPL V2
  license_family: GPL
  summary: Exploratory factor analysis in Python
